// flow-typed signature: 26191ca78db4209d18743d92c231fb74
// flow-typed version: <<STUB>>/libstl_v^0.1.22/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libstl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'libstl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libstl/Datastructures/DoublyLinkedList' {
  declare module.exports: any;
}

declare module 'libstl/Datastructures/Heap' {
  declare module.exports: any;
}

declare module 'libstl/Datastructures/MaxHeap' {
  declare module.exports: any;
}

declare module 'libstl/Datastructures/MinHeap' {
  declare module.exports: any;
}

declare module 'libstl/Datastructures/PriorityQueue' {
  declare module.exports: any;
}

declare module 'libstl/Datastructures/Queue' {
  declare module.exports: any;
}

declare module 'libstl/Datastructures/Stack' {
  declare module.exports: any;
}

declare module 'libstl/Datastructures/Trie' {
  declare module.exports: any;
}

declare module 'libstl/Docs/api' {
  declare module.exports: any;
}

declare module 'libstl/Docs/assets/js/api-filter' {
  declare module.exports: any;
}

declare module 'libstl/Docs/assets/js/api-list' {
  declare module.exports: any;
}

declare module 'libstl/Docs/assets/js/api-search' {
  declare module.exports: any;
}

declare module 'libstl/Docs/assets/js/apidocs' {
  declare module.exports: any;
}

declare module 'libstl/Docs/assets/js/yui-prettify' {
  declare module.exports: any;
}

declare module 'libstl/Docs/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

declare module 'libstl/node-module' {
  declare module.exports: any;
}

declare module 'libstl/test' {
  declare module.exports: any;
}

declare module 'libstl/Tests/doublylinkedlist' {
  declare module.exports: any;
}

declare module 'libstl/Tests/heap' {
  declare module.exports: any;
}

declare module 'libstl/Tests/maxheap' {
  declare module.exports: any;
}

declare module 'libstl/Tests/minheap' {
  declare module.exports: any;
}

declare module 'libstl/Tests/priorityqueue' {
  declare module.exports: any;
}

declare module 'libstl/Tests/queue' {
  declare module.exports: any;
}

declare module 'libstl/Tests/run' {
  declare module.exports: any;
}

declare module 'libstl/Tests/stack' {
  declare module.exports: any;
}

declare module 'libstl/Tests/trie' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libstl/Datastructures/DoublyLinkedList.js' {
  declare module.exports: $Exports<'libstl/Datastructures/DoublyLinkedList'>;
}
declare module 'libstl/Datastructures/Heap.js' {
  declare module.exports: $Exports<'libstl/Datastructures/Heap'>;
}
declare module 'libstl/Datastructures/MaxHeap.js' {
  declare module.exports: $Exports<'libstl/Datastructures/MaxHeap'>;
}
declare module 'libstl/Datastructures/MinHeap.js' {
  declare module.exports: $Exports<'libstl/Datastructures/MinHeap'>;
}
declare module 'libstl/Datastructures/PriorityQueue.js' {
  declare module.exports: $Exports<'libstl/Datastructures/PriorityQueue'>;
}
declare module 'libstl/Datastructures/Queue.js' {
  declare module.exports: $Exports<'libstl/Datastructures/Queue'>;
}
declare module 'libstl/Datastructures/Stack.js' {
  declare module.exports: $Exports<'libstl/Datastructures/Stack'>;
}
declare module 'libstl/Datastructures/Trie.js' {
  declare module.exports: $Exports<'libstl/Datastructures/Trie'>;
}
declare module 'libstl/Docs/api.js' {
  declare module.exports: $Exports<'libstl/Docs/api'>;
}
declare module 'libstl/Docs/assets/js/api-filter.js' {
  declare module.exports: $Exports<'libstl/Docs/assets/js/api-filter'>;
}
declare module 'libstl/Docs/assets/js/api-list.js' {
  declare module.exports: $Exports<'libstl/Docs/assets/js/api-list'>;
}
declare module 'libstl/Docs/assets/js/api-search.js' {
  declare module.exports: $Exports<'libstl/Docs/assets/js/api-search'>;
}
declare module 'libstl/Docs/assets/js/apidocs.js' {
  declare module.exports: $Exports<'libstl/Docs/assets/js/apidocs'>;
}
declare module 'libstl/Docs/assets/js/yui-prettify.js' {
  declare module.exports: $Exports<'libstl/Docs/assets/js/yui-prettify'>;
}
declare module 'libstl/Docs/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'libstl/Docs/assets/vendor/prettify/prettify-min'>;
}
declare module 'libstl/node-module.js' {
  declare module.exports: $Exports<'libstl/node-module'>;
}
declare module 'libstl/test.js' {
  declare module.exports: $Exports<'libstl/test'>;
}
declare module 'libstl/Tests/doublylinkedlist.js' {
  declare module.exports: $Exports<'libstl/Tests/doublylinkedlist'>;
}
declare module 'libstl/Tests/heap.js' {
  declare module.exports: $Exports<'libstl/Tests/heap'>;
}
declare module 'libstl/Tests/maxheap.js' {
  declare module.exports: $Exports<'libstl/Tests/maxheap'>;
}
declare module 'libstl/Tests/minheap.js' {
  declare module.exports: $Exports<'libstl/Tests/minheap'>;
}
declare module 'libstl/Tests/priorityqueue.js' {
  declare module.exports: $Exports<'libstl/Tests/priorityqueue'>;
}
declare module 'libstl/Tests/queue.js' {
  declare module.exports: $Exports<'libstl/Tests/queue'>;
}
declare module 'libstl/Tests/run.js' {
  declare module.exports: $Exports<'libstl/Tests/run'>;
}
declare module 'libstl/Tests/stack.js' {
  declare module.exports: $Exports<'libstl/Tests/stack'>;
}
declare module 'libstl/Tests/trie.js' {
  declare module.exports: $Exports<'libstl/Tests/trie'>;
}
