// flow-typed signature: 1d4c9930f503a7c3f21481f681425562
// flow-typed version: <<STUB>>/parsimmon_v^1.2.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parsimmon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'parsimmon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parsimmon/build/parsimmon.browser' {
  declare module.exports: any;
}

declare module 'parsimmon/build/parsimmon.browser.min' {
  declare module.exports: any;
}

declare module 'parsimmon/src/parsimmon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parsimmon/build/parsimmon.browser.js' {
  declare module.exports: $Exports<'parsimmon/build/parsimmon.browser'>;
}
declare module 'parsimmon/build/parsimmon.browser.min.js' {
  declare module.exports: $Exports<'parsimmon/build/parsimmon.browser.min'>;
}
declare module 'parsimmon/src/parsimmon.js' {
  declare module.exports: $Exports<'parsimmon/src/parsimmon'>;
}
