// flow-typed signature: 6f7694c5e9a1488d0c88c3c1c5717679
// flow-typed version: <<STUB>>/priorityqueuejs_v^1.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'priorityqueuejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'priorityqueuejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'priorityqueuejs/test/bootstrap' {
  declare module.exports: any;
}

declare module 'priorityqueuejs/test/priorityqueue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'priorityqueuejs/index' {
  declare module.exports: $Exports<'priorityqueuejs'>;
}
declare module 'priorityqueuejs/index.js' {
  declare module.exports: $Exports<'priorityqueuejs'>;
}
declare module 'priorityqueuejs/test/bootstrap.js' {
  declare module.exports: $Exports<'priorityqueuejs/test/bootstrap'>;
}
declare module 'priorityqueuejs/test/priorityqueue.js' {
  declare module.exports: $Exports<'priorityqueuejs/test/priorityqueue'>;
}
